# Build stage
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./

# Install all dependencies (including dev) for build
RUN npm ci

COPY . .

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Accept build-time environment variables for NEXT_PUBLIC_* vars
ARG NEXT_PUBLIC_BASE_RPC_URL
ARG NEXT_PUBLIC_MEGA_RPC_URL
ARG NEXT_PUBLIC_BASE_CHAIN_ID
ARG NEXT_PUBLIC_MEGA_CHAIN_ID
ARG NEXT_PUBLIC_BAD_BUNNZ_BASE
ARG NEXT_PUBLIC_BAD_BUNNZ_MEGA
ARG NEXT_PUBLIC_ETH_BRIDGE
ARG NEXT_PUBLIC_MEGA_BRIDGE
ARG NEXT_PUBLIC_API_BASE_URL
ARG NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID

# Set them as ENV so they're available during build
ENV NEXT_PUBLIC_BASE_RPC_URL=$NEXT_PUBLIC_BASE_RPC_URL
ENV NEXT_PUBLIC_MEGA_RPC_URL=$NEXT_PUBLIC_MEGA_RPC_URL
ENV NEXT_PUBLIC_BASE_CHAIN_ID=$NEXT_PUBLIC_BASE_CHAIN_ID
ENV NEXT_PUBLIC_MEGA_CHAIN_ID=$NEXT_PUBLIC_MEGA_CHAIN_ID
ENV NEXT_PUBLIC_BAD_BUNNZ_BASE=$NEXT_PUBLIC_BAD_BUNNZ_BASE
ENV NEXT_PUBLIC_BAD_BUNNZ_MEGA=$NEXT_PUBLIC_BAD_BUNNZ_MEGA
ENV NEXT_PUBLIC_ETH_BRIDGE=$NEXT_PUBLIC_ETH_BRIDGE
ENV NEXT_PUBLIC_MEGA_BRIDGE=$NEXT_PUBLIC_MEGA_BRIDGE
ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL
ENV NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=$NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID

# Build the application
RUN npm run build

# Production stage
FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Copy package files and install only production dependencies
COPY package*.json ./
RUN npm ci --omit=dev

# Copy built application from builder
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/next.config.ts ./
COPY --from=builder /app/tsconfig.json ./

EXPOSE 3000

CMD ["npm", "run", "start"]
